### PR TITLE
Demos now grow up to 600px to fit content

### PR DESCRIPTION
**Pull request by imaustink**
Fixes issue #4 and some whitespace inconsistency in the file.

### CODE REVIEW

**Comment by justinbmeyer** [comment]
I don't think this is going to work for when the content changes size

**Comment by leoj3n** [comment]
Ignoring `.DS_Store` should probably be done in your [global `.gitignore`](https://help.github.com/articles/ignoring-files/) since it's OS dependent.

Also, it would help with review if you made sweeping whitespace changes in a different commit.

Eventually we will have some hinting/linting that will fix everything up anyways (differently), so usually I avoid reformatting a file's whitespace unless completely rewriting that file's functionality.

Once #9 is merged you shouldn't be blocked on writing tests for this.

**Comment by leoj3n** [comment]
Is this something that needs to be merged? Lmk if you need help merging since this now has conflicting changes because of a PR I just merged.

**Comment by imaustink** [comment]
@leoj3n I honestly don't remember exactly what is going on with this. I think @justinbmeyer wanted a test for this but I think at the time this was implimented we were waiting for changes in `bit-docs` to make it more testable.

**Comment by leoj3n** [comment]
Well, I do see that I commented:

> Once #9 is merged you shouldn't be blocked on writing tests for this.

But that's kind of vague in retrospect, and I'm entirely sure what I meant there.

I guess you were blocked in writing tests for this because of #9?

Well, #9 is closed now, if that helps.

**Comment by leoj3n** [comment]
Oh yeah, I think running the test suite with Zombie was broken and I had resolved that in my test suite PR, so you were kind of waiting for that to be merged and available to write tests on top of.

**Comment by m-mujica** [comment]
Closed in favor of #13

**Pull request closed without merging**
